[package]
name = "vfhm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
fnv = "1"
phf = { version = "0.11", features = ["macros"] }
