[package]
name = "vfhm"
version = "0.1.0"
edition = "2021"

[features]
default = []

[[bench]]
name = "jquery"
harness = false

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
fnv = "1"

